# TODO: Update this once the backend split have been merged => Main images for every service exist
version: "3.9"
services:
  backend:
    image: node:18-alpine3.15
    restart: "always"
    volumes:
      - ./backend:/home/node
    ports:
      - 3001:3001
    working_dir: /home/node
    command: npm run start:dev
    depends_on:
      - mongodb
  frontend:
    image: node:18-alpine3.15
    restart: "always"
    volumes:
      - ./frontend:/home/node
    ports:
      - 3000:3000
    working_dir: /home/node
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PW}
      MONGO_INITDB_DATABASE: ${DB_MONGO_NAME}
    ports:
      - 27018:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - mongodb_data_container:/data/mongodb
  eventstore:
    image: eventstore/eventstore:20.6.1-buster-slim
    restart: "always"
    ports:
      - 3010:1113
      - 3011:2113
    volumes:
      - eventstore_data_container:/var/lib/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
  postgres:
    image: postgres:15
    restart: "always"
    volumes: 
      - postgres-volume:/var/lib/pgsql/data
      - ./db/setup:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_PG_USER}
      - POSTGRES_PASSWORD=${DB_PG_PW}
      - POSTGRES_DB=${DB_PG_DB}
    healthcheck:
      # TODO: This can be replaced by a more accurate healthcheck based on PID 1 
      test: ["CMD-SHELL","pg_isready"]
      interval: 60s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data_container:
  postgres-volume:
  eventstore_data_container:
