version: "3.9"
services:
  backend:
    image: node:18-alpine3.15
    restart: "always"
    volumes:
      - ./backend:/home/node
    ports:
      - 8081:3000
    working_dir: /home/node
    command: npm run start:dev
    depends_on:
      - db
  frontend:
    image: node:18-alpine3.15
    restart: "always"
    volumes:
      - ./frontend:/home/node
    ports:
      - 8080:3000
    working_dir: /home/node
    command: npm run dev
  db:
    image: postgres:15
    restart: "always"
    volumes: 
      - postgres-volume:/var/lib/pgsql/data
      - ./db/setup:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=${DB_DB}
    healthcheck:
      # TODO: This can be replaced by a more accurate healthcheck based on PID 1 
      test: ["CMD_SHELL","pg_isready"]
      interval: 60s
      timeout: 5s
      retries: 3

volumes:
  postgres-volume:




