version: "3.9"
services:
  backend:
    image: node:18-alpine3.15
    restart: "always"
    volumes:
      - ./backend:/home/node
    ports:
      - 3001:3000
    working_dir: /home/node
    command: npm run start:dev
    depends_on:
      - mongodb_container
  frontend:
    image: node:18-alpine3.15
    restart: "always"
    volumes:
      - ./frontend:/home/node
    ports:
      - 3000:3000
    working_dir: /home/node
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PW}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - 27018:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
