name: backend-pipeline

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/**.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:

      - name: where am i
       run: 'ls'

     - name: node modules
       run: 'npm ci'
    
     - name: end 2 end tests
       run: npm run test:e2e
       
     - name: unit tests
       run: npm run test
