name: backend-pipeline

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/**.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

     - name: Checkout repository
       uses: actions/checkout@v3
       with:
         path: backend

     - name: go to backend
       run: 'cd backend'

     - name: where am i
       run: 'ls'

     - name: node modules
       run: 'npm ci'
    
     - name: end 2 end tests
       run: npm run test:e2e
       
     - name: unit tests
       run: npm run test
