name: frontend-pipeline

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/**.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/**.yml'

jobs:
  single-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: node modules
        run: 'npm ci --audit:false'

      - name: Cypress run
        uses: cypress-io/github-action@v4
        timeout-minutes: 15
        with:
          build: npm run build
          start: npm start
